---

image: python:3.13

stages:
  - build
  - lint

Build and Test:
  stage: build
  script:
    - pip install uv
    - uv sync
    - ls -la
    - uv run python hello-world.py
    - echo "The code is okay"

lint:
  stage: lint
  script:
    - pip install uv
    - uv sync
    - uv run flake8 . --exclude=.git,.venv --show-source --statistics
