---

image: python:3.13

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          script:
            - pip install uv
            - uv sync
            - ls -la
            - uv run hello-world.py
            - echo "The code is okay"
      - step:
          name: Lint code
          script:
            - pip install uv
            - uv sync
            - uv run flake8 . --exclude=.git,.venv --show-source --statistics
